package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Customer generated by hbm2java
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties({"createdTs", "modifiedTs", "orders"})
public class Customer implements java.io.Serializable {

	private int custId;
	private String custname;
	private String address;
	private Integer phoneNo;
	private String EMail;
	private Date regDate;
	private Date createdTs;
	private Date modifiedTs;
	private Set orders = new HashSet(0);

	public Customer() {
	}

	public Customer(int custId) {
		this.custId = custId;
	}

	public Customer(int custId, String custname, String address, Integer phoneNo, String EMail, Date regDate,
			Date createdTs, Date modifiedTs, Set orders) {
		this.custId = custId;
		this.custname = custname;
		this.address = address;
		this.phoneNo = phoneNo;
		this.EMail = EMail;
		this.regDate = regDate;
		this.createdTs = createdTs;
		this.modifiedTs = modifiedTs;
		this.orders = orders;
	}

	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public String getCustname() {
		return this.custname;
	}

	public void setCustname(String custname) {
		this.custname = custname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
