package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int empId;
	private String empName;
	private Character gender;
	private String address;
	private Integer phoneNo;
	private String emailAddress;
	private String designation;
	private Date doj;
	private Date dob;
	private Integer salary;
	private Integer age;
	private Date createdTs;
	private Date modifiedTs;

	public Employee() {
	}

	public Employee(int empId) {
		this.empId = empId;
	}

	public Employee(int empId, String empName, Character gender, String address, Integer phoneNo, String emailAddress,
			String designation, Date doj, Date dob, Integer salary, Integer age, Date createdTs, Date modifiedTs) {
		this.empId = empId;
		this.empName = empName;
		this.gender = gender;
		this.address = address;
		this.phoneNo = phoneNo;
		this.emailAddress = emailAddress;
		this.designation = designation;
		this.doj = doj;
		this.dob = dob;
		this.salary = salary;
		this.age = age;
		this.createdTs = createdTs;
		this.modifiedTs = modifiedTs;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

}
