package com.stockie.model;
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private int id;
	private String name;
	private String manu;
	private BigDecimal weight;
	private BigDecimal price;
	private Integer popularity;
	private String includes;
	private Date lastModified;

	public Item() {
	}

	public Item(int id) {
		this.id = id;
	}

	public Item(int id, String name, String manu, BigDecimal weight, BigDecimal price, Integer popularity,
			String includes, Date lastModified) {
		this.id = id;
		this.name = name;
		this.manu = manu;
		this.weight = weight;
		this.price = price;
		this.popularity = popularity;
		this.includes = includes;
		this.lastModified = lastModified;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getManu() {
		return this.manu;
	}

	public void setManu(String manu) {
		this.manu = manu;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	public String getIncludes() {
		return this.includes;
	}

	public void setIncludes(String includes) {
		this.includes = includes;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
