package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Layout generated by hbm2java
 */
public class Layout implements java.io.Serializable {

	private int layoutId;
	private String layoutName;
	private Integer totalTabs;
	private Integer totalPages;
	private Date createdTs;
	private Date modifiedTs;
	private Set layoutDetails = new HashSet(0);

	public Layout() {
	}

	public Layout(int layoutId) {
		this.layoutId = layoutId;
	}

	public Layout(int layoutId, String layoutName, Integer totalTabs, Integer totalPages, Date createdTs,
			Date modifiedTs, Set layoutDetails) {
		this.layoutId = layoutId;
		this.layoutName = layoutName;
		this.totalTabs = totalTabs;
		this.totalPages = totalPages;
		this.createdTs = createdTs;
		this.modifiedTs = modifiedTs;
		this.layoutDetails = layoutDetails;
	}

	public int getLayoutId() {
		return this.layoutId;
	}

	public void setLayoutId(int layoutId) {
		this.layoutId = layoutId;
	}

	public String getLayoutName() {
		return this.layoutName;
	}

	public void setLayoutName(String layoutName) {
		this.layoutName = layoutName;
	}

	public Integer getTotalTabs() {
		return this.totalTabs;
	}

	public void setTotalTabs(Integer totalTabs) {
		this.totalTabs = totalTabs;
	}

	public Integer getTotalPages() {
		return this.totalPages;
	}

	public void setTotalPages(Integer totalPages) {
		this.totalPages = totalPages;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	public Set getLayoutDetails() {
		return this.layoutDetails;
	}

	public void setLayoutDetails(Set layoutDetails) {
		this.layoutDetails = layoutDetails;
	}

}
