package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * OrderPayment generated by hbm2java
 */
public class OrderPayment implements java.io.Serializable {

	private long ordPayId;
	private Order orders;
	private String payType;
	private String ccType;
	private BigDecimal totalAmount;
	private BigDecimal changeReturn;
	private BigDecimal oldBalance;
	private Date paymentDate;

	public OrderPayment() {
	}

	public OrderPayment(long ordPayId) {
		this.ordPayId = ordPayId;
	}

	public OrderPayment(long ordPayId, Order orders, String payType, String ccType, BigDecimal totalAmount,
			BigDecimal changeReturn, BigDecimal oldBalance, Date paymentDate) {
		this.ordPayId = ordPayId;
		this.orders = orders;
		this.payType = payType;
		this.ccType = ccType;
		this.totalAmount = totalAmount;
		this.changeReturn = changeReturn;
		this.oldBalance = oldBalance;
		this.paymentDate = paymentDate;
	}

	public long getOrdPayId() {
		return this.ordPayId;
	}

	public void setOrdPayId(long ordPayId) {
		this.ordPayId = ordPayId;
	}

	public Order getOrders() {
		return this.orders;
	}

	public void setOrders(Order orders) {
		this.orders = orders;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getCcType() {
		return this.ccType;
	}

	public void setCcType(String ccType) {
		this.ccType = ccType;
	}

	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public BigDecimal getChangeReturn() {
		return this.changeReturn;
	}

	public void setChangeReturn(BigDecimal changeReturn) {
		this.changeReturn = changeReturn;
	}

	public BigDecimal getOldBalance() {
		return this.oldBalance;
	}

	public void setOldBalance(BigDecimal oldBalance) {
		this.oldBalance = oldBalance;
	}

	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

}
