package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int prodId;
	private ProductBrand productBrand;
	private ProductType productType;
	private String prodName;
	private Integer quantity;
	private BigDecimal price;
	private Integer quantitySold;
	private Integer totalQuantity;
	private String activeFlag;
	private String brandName;
	private Set layoutDetails = new HashSet(0);
	private Set orderItems = new HashSet(0);

	public Product() {
	}

	public Product(int prodId) {
		this.prodId = prodId;
	}

	public Product(int prodId, ProductBrand productBrand, ProductType productType, String prodName, Integer quantity,
			BigDecimal price, Integer quantitySold, Integer totalQuantity, String activeFlag, String brandName,
			Set layoutDetails, Set orderItems) {
		this.prodId = prodId;
		this.productBrand = productBrand;
		this.productType = productType;
		this.prodName = prodName;
		this.quantity = quantity;
		this.price = price;
		this.quantitySold = quantitySold;
		this.totalQuantity = totalQuantity;
		this.activeFlag = activeFlag;
		this.brandName = brandName;
		this.layoutDetails = layoutDetails;
		this.orderItems = orderItems;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public ProductBrand getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(ProductBrand productBrand) {
		this.productBrand = productBrand;
	}

	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getQuantitySold() {
		return this.quantitySold;
	}

	public void setQuantitySold(Integer quantitySold) {
		this.quantitySold = quantitySold;
	}

	public Integer getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(Integer totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public Set getLayoutDetails() {
		return this.layoutDetails;
	}

	public void setLayoutDetails(Set layoutDetails) {
		this.layoutDetails = layoutDetails;
	}

	public Set getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set orderItems) {
		this.orderItems = orderItems;
	}

}
