package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

	private int productTypeId;
	private String typeDesc;
	private Set products = new HashSet(0);

	public ProductType() {
	}

	public ProductType(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	public ProductType(int productTypeId, String typeDesc, Set products) {
		this.productTypeId = productTypeId;
		this.typeDesc = typeDesc;
		this.products = products;
	}

	public int getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getTypeDesc() {
		return this.typeDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
