package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProductBrand generated by hbm2java
 */
public class ProductBrand implements java.io.Serializable {

	private int brandId;
	private String brandName;
	private Set products = new HashSet(0);

	public ProductBrand() {
	}

	public ProductBrand(int brandId) {
		this.brandId = brandId;
	}

	public ProductBrand(int brandId, String brandName, Set products) {
		this.brandId = brandId;
		this.brandName = brandName;
		this.products = products;
	}

	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
