package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

/**
 * TbUsers generated by hbm2java
 */
public class TbUser implements java.io.Serializable {

	private Long userId;
	private Integer enabled;
	private String password;
	private String userName;

	public TbUser() {
	}

	public TbUser(Integer enabled, String password, String userName) {
		this.enabled = enabled;
		this.password = password;
		this.userName = userName;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
