package com.stockie.model;

// default package
// Generated Jun 25, 2017 1:53:14 PM by Hibernate Tools 5.2.3.Final

/**
 * UserRoles generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private int userRoleId;
	private User users;
	private String role;

	public UserRole() {
	}

	public UserRole(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRole(int userRoleId, User users, String role) {
		this.userRoleId = userRoleId;
		this.users = users;
		this.role = role;
	}

	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
