CREATE TABLE stockie.CUSTOMER (
	CUST_ID INTEGER NOT NULL,
	CUSTNAME VARCHAR(100),
	ADDRESS VARCHAR(255),
	PHONE_NO INTEGER,
	E_MAIL VARCHAR(60),
	REG_DATE DATE,
	CREATED_TS TIMESTAMP,
	MODIFIED_TS TIMESTAMP,
	CONSTRAINT CONSTRAINT_5 PRIMARY KEY (CUST_ID)
) ;

CREATE TABLE stockie.EMPLOYEE (
	EMP_ID INTEGER NOT NULL,
	EMP_NAME VARCHAR(100),
	GENDER CHAR(1),
	ADDRESS VARCHAR(255),
	PHONE_NO INTEGER,
	EMAIL_ADDRESS VARCHAR(60),
	DESIGNATION VARCHAR(60),
	DOJ DATE,
	DOB DATE,
	SALARY INTEGER,
	AGE INTEGER,
	CREATED_TS TIMESTAMP,
	MODIFIED_TS TIMESTAMP,
	CONSTRAINT CONSTRAINT_7 PRIMARY KEY (EMP_ID)
) ;


CREATE TABLE stockie.ITEM (
	ID INTEGER NOT NULL,
	NAME VARCHAR(100),
	MANU VARCHAR(50),
	WEIGHT DECIMAL(10,2),
	PRICE DECIMAL(10,2),
	POPULARITY INTEGER,
	INCLUDES VARCHAR(200),
	LAST_MODIFIED TIMESTAMP,
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
) ;


CREATE TABLE stockie.ORDERS (
	ORDER_ID INTEGER NOT NULL,
	CUST_ID INTEGER,
	ORDER_DATE DATE,
	DISCOUNT DECIMAL(10,2),
	STATUS VARCHAR(40),
	CREATED_TS TIMESTAMP,
	MODIFIED_TS TIMESTAMP,
	NOTES VARCHAR(255),
	PAY_TYPE VARCHAR(50),
	CC_TYPE VARCHAR(50),
	TOTAL_AMOUNT DECIMAL(30,2),
	CHANGE_RETURN DECIMAL(10,2),
	PAYMENT_DATE DATE,
	NET_AMOUNT DOUBLE,
	OLD_BALANCE DOUBLE,
	SUB_TOTAL DOUBLE,
	TAX BIGINT,
	RECEIVED_AMOUNT DECIMAL(30,2),
	CONSTRAINT CONSTRAINT_8B PRIMARY KEY (ORDER_ID),
	CONSTRAINT CONSTRAINT_8B7 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK8D444F059BFCED73 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;
CREATE INDEX CONSTRAINT_8B7_INDEX_3 ON ORDERS (CUST_ID) ;
CREATE UNIQUE INDEX FK_ORDER_INDEX_3 ON ORDERS (ORDER_ID) ;

CREATE TABLE stockie.ORDER_ITEMS (
	ID INTEGER NOT NULL,
	ORDER_ID INTEGER,
	PROD_ID INTEGER,
	AMOUNT DECIMAL(30,0),
	QUANTITY INTEGER,
	CONSTRAINT CONSTRAINT_2B PRIMARY KEY (ID),
	CONSTRAINT CONSTRAINT_2BF FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT CONSTRAINT_2BFF FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK2BFF474F1EDE6724 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

CREATE TABLE stockie.ORDER_PAYMENT (
	ORD_PAY_ID DECIMAL(10,0) NOT NULL,
	ORDER_ID DECIMAL(10,0),
	PAY_TYPE VARCHAR(50),
	CC_TYPE VARCHAR(50),
	TOTAL_AMOUNT DECIMAL(10,2),
	CHANGE_RETURN DECIMAL(10,2),
	OLD_BALANCE DECIMAL(10,2),
	PAYMENT_DATE DATE,
	CONSTRAINT CONSTRAINT_7C PRIMARY KEY (ORD_PAY_ID),
	CONSTRAINT FK_ORD_PAYMENT FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

CREATE TABLE stockie.PRODUCT (
	PROD_ID INTEGER NOT NULL,
	PROD_NAME VARCHAR(100),
	QUANTITY INTEGER,
	PRICE DECIMAL(10,2),
	QUANTITY_SOLD INTEGER,
	TOTAL_QUANTITY INTEGER,
	TYPE_ID INTEGER,
	BRAND_ID INTEGER,
	ACTIVE_FLAG VARCHAR(1),
	BRAND_NAME VARCHAR(255),
	CONSTRAINT CONSTRAINT_18 PRIMARY KEY (PROD_ID),
	CONSTRAINT CONSTRAINT_185 FOREIGN KEY (TYPE_ID) REFERENCES PRODUCT_TYPE(PRODUCT_TYPE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT CONSTRAINT_1859 FOREIGN KEY (BRAND_ID) REFERENCES PRODUCT_BRAND(BRAND_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;

CREATE TABLE stockie.PRODUCT_BRAND (
	BRAND_ID INTEGER NOT NULL,
	BRAND_NAME VARCHAR(100),
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (BRAND_ID)
) ;

CREATE TABLE stockie.PRODUCT_TYPE (
	PRODUCT_TYPE_ID INTEGER NOT NULL,
	TYPE_DESC VARCHAR(255),
	CONSTRAINT CONSTRAINT_C PRIMARY KEY (PRODUCT_TYPE_ID)
) ;

CREATE TABLE stockie.USERS (
	USER_ID INTEGER NOT NULL,
	USER_NAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	ENABLED INTEGER,
	CREATED_TS TIMESTAMP,
	MODIFIED_TS TIMESTAMP,
	CONSTRAINT CONSTRAINT_4D PRIMARY KEY (USER_ID)
) ;
CREATE UNIQUE INDEX UNI_USERNAME_INDEX_B ON USERS (USER_NAME) ;

CREATE TABLE stockie.USER_ROLES (
	USER_ROLE_ID INTEGER NOT NULL,
	USER_NAME VARCHAR(45),
	"ROLE" VARCHAR(45),
	CONSTRAINT CONSTRAINT_C6 PRIMARY KEY (USER_ROLE_ID),
	CONSTRAINT FK_USERNAME FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;
CREATE INDEX FK_USERNAME_INDEX_C ON USER_ROLES (USER_NAME) ;
CREATE UNIQUE INDEX UNI_USERNAME_ROLE_INDEX_C ON USER_ROLES ("ROLE",USER_NAME) ;

CREATE TABLE stockie.LAYOUT (
	LAYOUT_ID INTEGER NOT NULL,
	LAYOUT_NAME VARCHAR(50),
	TOTAL_TABS INTEGER,
	TOTAL_PAGES INTEGER,
	CREATED_TS TIMESTAMP,
	MODIFIED_TS TIMESTAMP,
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY (LAYOUT_ID)
) ;

CREATE TABLE stockie.LAYOUT_DETAILS (
	LAYOUT_DETAIL_ID INTEGER NOT NULL,
	PROD_ID INTEGER,
	PAGE_NO INTEGER,
	TAB_NO INTEGER,
	COLOR_CODE VARCHAR(20),
	LAYOUT_ID INTEGER,
	CREATED_TS TIMESTAMP,
	MODIFIED_TS TIMESTAMP,
	CONSTRAINT CONSTRAINT_1 PRIMARY KEY (LAYOUT_DETAIL_ID),
	CONSTRAINT CONSTRAINT_13 FOREIGN KEY (LAYOUT_ID) REFERENCES LAYOUT(LAYOUT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK137D4A0D1EDE6724 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES LAYOUT(LAYOUT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_LAYOUT_PROD FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;